#!/bin/sh

WORKDIR="`cd \`dirname $0\` && pwd`"

if [ $# -ne 3 ]; then
	echo "usage: build cert-directory output-file config-basename"
	exit 1
fi

CERTDIR=$1
OUT_PATH=$2
CONFIG_BASENAME=$3
TMPDIR=/tmp/installer.$$

if [ ! -d $CERTDIR ]; then
	echo "error: $CERTDIR does not appear to be a certificate directory"
	exit 1
fi

if [ ! -d $TMPDIR ]; then
	mkdir -p $TMPDIR
fi

cp $CERTDIR/* $TMPDIR
#XXX RENAME CERTS
# perform some fancy substitution
sed -e "s/_CONFIG_/$CONFIG_BASENAME/g" < $TMPDIR/client.conf > $TMPDIR/$CONFIG_BASENAME.conf
rm -f $TMPDIR/client.conf

mv $TMPDIR/client.crt $TMPDIR/$CONFIG_BASENAME.crt
mv $TMPDIR/client.key $TMPDIR/$CONFIG_BASENAME.key
mv $TMPDIR/ca.crt $TMPDIR/$CONFIG_BASENAME-ca.crt
mv $TMPDIR/ta.key $TMPDIR/$CONFIG_BASENAME-ta.key

cd $TMPDIR && zip -0r $CONFIG_BASENAME.vpex *.conf *.crt *.key
STATUS=$?

if [ $STATUS -eq 0 ]; then
	mv $TMPDIR/$CONFIG_BASENAME.vpex $OUT_PATH
fi

rm -rf $TMPDIR
exit $STATUS
