#!/bin/sh

# $0 = Script path
# $1 = Package path
# $2 = Target location
# $3 = Target volume

#########################
# postflight for VPEx app
#########################

touch /tmp/FOO_POSTFLIGHT_RAN

pushd /Applications/VPExExecutor.app >/dev/null
#chown -R 0:0 .
#find . -type d -exec chmod 775 "{}" \;
#find . -type f -exec chmod 664 "{}" \;
chmod 775 Contents/MacOS/VPExConnectionManager
chown 0:0 Contents/PlugIns/openvpn
chmod 4711 Contents/PlugIns/openvpn
popd

####################
# postflight for tun
####################

touch /tmp/POSTFLIGHT_RAN

# old versions resided in /System/Library, remove.
rm -r /System/Library/Extensions/tun.kext

# unload an old extension (might fail)
kextunload /Library/Extensions/tun.kext

# Fix ownership. The installer gets this wrong *sigh*
chown -R root:wheel /Library/Extensions/tun.kext
chmod -R u=rwX,g=rX,o=rX /Library/Extensions/tun.kext

# load the new version
kextload /Library/Extensions/tun.kext

####################
# postflight for tap
####################

# old versions resided in /System/Library, remove.
rm -r /System/Library/Extensions/tap.kext

# unload an old extension (might fail)
kextunload /Library/Extensions/tap.kext

# Fix ownership and permissions. PackageMaker gets this wrong *sigh*
chown -R root:wheel /Library/Extensions/tap.kext
chmod -R u=rwX,g=rX,o=rX /Library/Extensions/tap.kext

# load the new version
kextload /Library/Extensions/tap.kext

#################################
# postflight for tun startup item
#################################

# old versions resided in /System/Library, remove.
rm -r /System/Library/StartupItems/tun

# Fix ownership and permissions. PackageMaker gets this wrong *sigh*
chown -R root:wheel /Library/StartupItems/tun
chmod -R u=rwX,g=rX,o=rX /Library/StartupItems/tun

#################################
# postflight for tap startup item
#################################

# old versions resided in /System/Library, remove.
rm -r /System/Library/StartupItems/tap

# Fix ownership and permissions. PackageMaker gets this wrong *sigh*
chown -R root:wheel /Library/StartupItems/tap
chmod -R u=rwX,g=rX,o=rX /Library/StartupItems/tap

# exit successfully
exit 0
