#!/bin/bash

WORKDIR="`cd \`dirname $0\` && pwd`"

# glean version #
VERSION="`grep ^VERSION $WORKDIR/../VERSION | cut -d: -f2`"
BUILD="`grep ^BUILD $WORKDIR/../VERSION | cut -d: -f2`"

echo "Previous: VERSION=$VERSION BUILD=$BUILD"

# bump build number
BUILD=$((BUILD + 1))

echo "Bumped to: VERSION=$VERSION BUILD=$BUILD"

cat << _EOF_ > $WORKDIR/../VERSION
VERSION:$VERSION
BUILD:$BUILD
_EOF_

cd $WORKDIR/.. && git commit -m "Bump build number" VERSION
